[project]
name = 'molecular-assembly-manufacturing-dao'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.molecular-blueprint-registry]
path = 'contracts/molecular-blueprint-registry.clar'
clarity_version = 3
epoch = 3.1

[contracts.nano-manufacturing-incentivizer]
path = 'contracts/nano-manufacturing-incentivizer.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
